package com;

import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GAMING PC
 */
public class Calculator extends javax.swing.JFrame {
    
    double first;
    double second;
    double result;
    String operations;
    
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        try {
			setIconImage(ImageIO.read(new File("C:\\Eclipse\\HomeScreen\\src\\com\\Guoba.png")));
			
		}	
		catch(IOException e) {
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSignChange = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jTextFieldDisplay = new javax.swing.JTextField();
        jButtonDivide1 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 560));
        setPreferredSize(new java.awt.Dimension(425, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSignChange.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jButtonSignChange.setText("+/-");
        jButtonSignChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignChangeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSignChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 90, 90));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 90));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 90, 90));

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 90, 90));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 90));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, 90));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, 90));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 90));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 90, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 90, 90));

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, 90));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 90, 90));

        jButtonDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 90, 90));

        jButtonEquals.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonEquals.setText("=");
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 190, 70));

        jButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 90, 90));

        jButtonMultiply.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonMultiply.setText("*");
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 90, 90));

        jTextFieldDisplay.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(jTextFieldDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 60));

        jButtonDivide1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonDivide1.setText("/");
        jButtonDivide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivide1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 90, 90));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSignChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignChangeActionPerformed
        double sign = Double.parseDouble(String.valueOf(jTextFieldDisplay.getText()));
        sign = sign * (-1);
        jTextFieldDisplay.setText(String.valueOf(sign));
        
    }//GEN-LAST:event_jButtonSignChangeActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton9.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton9.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton8.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton8.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        first = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton4.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton4.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton5.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton5.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton6.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton6.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton3.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton3.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton2.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton2.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton1.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton1.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton0.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton0.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButton7.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButton7.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        String inputNumber = jTextFieldDisplay.getText();
        
        if(inputNumber == ""){
            jTextFieldDisplay.setText(jButtonDot.getText());
            
        } else {
            inputNumber = jTextFieldDisplay.getText() + jButtonDot.getText();
            jTextFieldDisplay.setText(inputNumber);
            
        }
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        String answer;
        
        second = Double.parseDouble(jTextFieldDisplay.getText());
        
        if(operations == "+"){
            result = first + second;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        } else if (operations == "-"){
            result = first - second;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        } else if (operations == "*"){
            result = first * second;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        } else if (operations == "/"){
            result = first / second;
            answer = String.format("%.2f", result);
            jTextFieldDisplay.setText(answer);
        }
            
        
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        first = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        first = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_jButtonMultiplyActionPerformed

    private void jButtonDivide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivide1ActionPerformed
        first = Double.parseDouble(jTextFieldDisplay.getText());
        jTextFieldDisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_jButtonDivide1ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldDisplay.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDivide1;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonSignChange;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
