package com;

import java.io.File;
import java.io.IOException;
import java.text.MessageFormat;

import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GAMING PC
 */
public class HomeScreen extends javax.swing.JFrame {
    
    /**
     * Creates new form homeScreenFrame
     */
    public HomeScreen() {
        initComponents();
        try {
			setIconImage(ImageIO.read(new File("C:\\Eclipse\\HomeScreen\\src\\com\\Guoba.png")));
			
		}	
		catch(IOException e) {
			e.printStackTrace();
		}
    }
    
    Calculator calcu = new Calculator();
    OrderHistory order = new OrderHistory();

    
    String name = null;
    int qty = 0;
    double value = 0;
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSignOut = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonHistory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jTextFieldCash = new javax.swing.JTextField();
        jTextFieldChange = new javax.swing.JTextField();
        jTextFieldDiscount = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonFoodItem7 = new javax.swing.JButton();
        jButtonDrinkItem7 = new javax.swing.JButton();
        jButtonFoodItem2 = new javax.swing.JButton();
        jButtonFoodItem3 = new javax.swing.JButton();
        jButtonFoodItem4 = new javax.swing.JButton();
        jButtonFoodItem5 = new javax.swing.JButton();
        jButtonFoodItem6 = new javax.swing.JButton();
        jButtonFoodItem1 = new javax.swing.JButton();
        jButtonFoodItem8 = new javax.swing.JButton();
        jButtonFoodItem9 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButtonDrinkItem1 = new javax.swing.JButton();
        jButtonDrinkItem2 = new javax.swing.JButton();
        jButtonDrinkItem3 = new javax.swing.JButton();
        jButtonDrinkItem4 = new javax.swing.JButton();
        jButtonDrinkItem6 = new javax.swing.JButton();
        jButtonDrinkItem5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonDeleteOrder = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButtonAddOrder = new javax.swing.JButton();
        jButtonVoidItem = new javax.swing.JButton();
        jButtonPay = new javax.swing.JButton();
        jButtonCalc = new javax.swing.JButton();
        jButtonDiscount = new javax.swing.JToggleButton();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSignOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSignOut.setText("Sign Out");
        jButtonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignOutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, 40));

        jButtonHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        jButtonMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMenu.setText(" Menu");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 40));

        jButtonHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonHistory.setText("History");
        jButtonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 20, 280, 390));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 60));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 300, 580));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 60));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 60));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 300, 580));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 300, 580));

        jPanel12.setBackground(new java.awt.Color(255, 255, 216));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SubTotal");
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cash");
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Change");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Discount");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 30));

        jTextFieldSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldSubTotal.setText("0.00");
        jTextFieldSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubTotalActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, 30));

        jTextFieldCash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCash.setText("0.00");
        jTextFieldCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCashActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 30));

        jTextFieldChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldChange.setText("0.00");
        jTextFieldChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChangeActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 30));

        jTextFieldDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldDiscount.setText("0.00");
        jTextFieldDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiscountActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 30));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, 150));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 300, 580));

        jPanel3.setBackground(new java.awt.Color(0, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFoodItem7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MoraMeat.jpg"))); // NOI18N
        jButtonFoodItem7.setText("7");
        jButtonFoodItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 90));

        jButtonDrinkItem7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDrinkItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinkItem7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDrinkItem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 90, 90));

        jButtonFoodItem2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BlackBackPerchStew.jpg"))); // NOI18N
        jButtonFoodItem2.setText("2");
        jButtonFoodItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 90));

        jButtonFoodItem3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/CrabRoeTofu.jpg"))); // NOI18N
        jButtonFoodItem3.setText("3");
        jButtonFoodItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 90));

        jButtonFoodItem4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JadeParcels.jpg"))); // NOI18N
        jButtonFoodItem4.setText("4");
        jButtonFoodItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 90));

        jButtonFoodItem5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/JewelrySoup.jpg"))); // NOI18N
        jButtonFoodItem5.setText("5");
        jButtonFoodItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 90, 90));

        jButtonFoodItem6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Jueyun.jpg"))); // NOI18N
        jButtonFoodItem6.setText("6");
        jButtonFoodItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 90, 90));

        jButtonFoodItem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/almondtofu.jpg"))); // NOI18N
        jButtonFoodItem1.setText("1");
        jButtonFoodItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jButtonFoodItem8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/NoodleDelicacy.jpg"))); // NOI18N
        jButtonFoodItem8.setText("8");
        jButtonFoodItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 90));

        jButtonFoodItem9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFoodItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SquirrelFish.jpg"))); // NOI18N
        jButtonFoodItem9.setText("9");
        jButtonFoodItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoodItem9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFoodItem9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, 90));

        jButton41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 90, 90));

        jButton44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 90, 90));

        jButton45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 90, 90));

        jButton46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, 90));

        jButton47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 90, 90));

        jButtonDrinkItem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDrinkItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WolfHookJuice.jpg"))); // NOI18N
        jButtonDrinkItem1.setText("1");
        jButtonDrinkItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinkItem1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDrinkItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 90, 90));

        jButtonDrinkItem2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDrinkItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/RainbowAster.jpg"))); // NOI18N
        jButtonDrinkItem2.setText("2");
        jButtonDrinkItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinkItem2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDrinkItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 90, 90));

        jButtonDrinkItem3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDrinkItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/HouseBlendIcedTea.jpg"))); // NOI18N
        jButtonDrinkItem3.setText("3");
        jButtonDrinkItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinkItem3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDrinkItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, 90));

        jButtonDrinkItem4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDrinkItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/DangoMilk.jpg"))); // NOI18N
        jButtonDrinkItem4.setText("4");
        jButtonDrinkItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinkItem4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDrinkItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 90, 90));

        jButtonDrinkItem6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDrinkItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/AppleCider.jpg"))); // NOI18N
        jButtonDrinkItem6.setText("6");
        jButtonDrinkItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinkItem6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDrinkItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 90, 90));

        jButtonDrinkItem5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDrinkItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BerryMintBurst.jpg"))); // NOI18N
        jButtonDrinkItem5.setText("5");
        jButtonDrinkItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrinkItem5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDrinkItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 90, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 770, 330));

        jPanel4.setBackground(new java.awt.Color(0, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDeleteOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDeleteOrder.setText("Clear");
        jButtonDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteOrderActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonDeleteOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 130, 60));

        jButtonPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 60));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton15.setText("Calculate");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 130, 60));

        jButtonAddOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAddOrder.setText("Save Order");
        jButtonAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOrderActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 60));

        jButtonVoidItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonVoidItem.setText("Void Item");
        jButtonVoidItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoidItemActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonVoidItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, 60));

        jButtonPay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPay.setText("Pay");
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 130, 60));

        jButtonCalc.setBackground(new java.awt.Color(204, 204, 0));
        jButtonCalc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCalc.setText("Calculate");
        jButtonCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 60));

        jButtonDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDiscount.setText("Discount");
        jButtonDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscountActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 130, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 770, 160));

        jPanel13.setBackground(new java.awt.Color(255, 255, 216));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        setVisible(true);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   public void ItemCost(){
       double sum = 0;
       
       for(int i = 0; i < jTable1.getRowCount(); i++){
       
           sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
           
           jTextFieldSubTotal.setText(Double.toString(sum));
           double cTotal = Double.parseDouble(jTextFieldSubTotal.getText());
           
           String iSubTotal = String.format("%.2f", cTotal);
           jTextFieldSubTotal.setText(iSubTotal);
           
       } 
   } 
    
    
   public void Change(){
       double sum = 0;
       double cash = Double.parseDouble(jTextFieldCash.getText());
       
       for(int i = 0; i <jTable1.getRowCount(); i++){
           
           sum += Double.parseDouble(jTable1.getValueAt(i, 2).toString());
           
           double cChange = cash - sum;
           
           
           String ChangeGiven = String.format("%.2f", cChange);
           jTextFieldChange.setText(ChangeGiven);
           
       }
   }
   
   public void Discount(){
       
           double subTotal = Double.parseDouble(jTextFieldSubTotal.getText());
           double cash = Double.parseDouble(jTextFieldCash.getText());
           
           double cDiscount =  (subTotal * 0.2);
           double FinalDiscount = subTotal - cDiscount;
           
           String Discount = String.format("%.2f", cDiscount);
           jTextFieldDiscount.setText(Discount);
           
           String DiscountGiven = String.format("%.2f", cash - FinalDiscount);
           jTextFieldChange.setText(DiscountGiven);
   }
   
    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jButtonDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteOrderActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jTextFieldChange.setText("0.00");
        jTextFieldSubTotal.setText("0.00");
        jTextFieldDiscount.setText("0.00");
        jTextFieldCash.setText("0.00");
    }//GEN-LAST:event_jButtonDeleteOrderActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress!");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch(java.awt.print.PrinterException e) {
            System.err.format("No printer found!", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOrderActionPerformed
        String d = "";
        String data = "";
        String costs = "";
        
        for(int i = 0; i < jTable1.getRowCount(); i++){
            name = (String) jTable1.getValueAt(i, 0);
            qty = Integer.parseInt(jTable1.getValueAt(i, 1).toString()); 
            value = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
    
            
            
            data = "x" + qty + " " + name + " " + "Php "+ value;

            d += " " + data + "\n";

      }
        
        double subTotal = Double.parseDouble(jTextFieldSubTotal.getText());
        double cash = Double.parseDouble(jTextFieldCash.getText());
        double discount = Double.parseDouble(jTextFieldDiscount.getText());
        double change = Double.parseDouble(jTextFieldChange.getText());
            
        costs = "\nCost: " + subTotal + "\n"
                    + "Cash Paid: " + cash + "\n"
                    + "Discount: " + discount + "\n" 
                    + "Checkout: " + change;
        
        if("".equals(order.getGUI().getText())){
                order.getGUI().setText(d + costs);
            } else if ("".equals(order.getGUI2().getText())){
                order.getGUI2().setText(order.getGUI().getText());
                order.getGUI().setText(d + costs);
                
            } else if ("".equals(order.getGUI3().getText())){
                order.getGUI3().setText(order.getGUI2().getText());
                order.getGUI2().setText(order.getGUI().getText());
                order.getGUI().setText(d + costs);
                
            } else if ("".equals(order.getGUI4().getText())){
                order.getGUI4().setText(order.getGUI2().getText());
                order.getGUI3().setText(order.getGUI2().getText());
                order.getGUI2().setText(order.getGUI().getText());
                order.getGUI().setText(d + costs);
            } else {
                order.getGUI4().setText(order.getGUI3().getText());
                order.getGUI3().setText(order.getGUI2().getText());
                order.getGUI2().setText(order.getGUI().getText());
                order.getGUI().setText(d + costs);
            }
        
        JOptionPane.showMessageDialog(null, "The current order has been saved in the History tab!", "Order Added", 1);
        
    }//GEN-LAST:event_jButtonAddOrderActionPerformed

    private void jButtonVoidItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoidItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int removeItem = jTable1.getSelectedRow();
        
        if(removeItem >= 0){
            model.removeRow(removeItem);
        }
        
        ItemCost();
        
    }//GEN-LAST:event_jButtonVoidItemActionPerformed

    private void jTextFieldCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCashActionPerformed

    private void jButtonFoodItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem7ActionPerformed
        double PriceOfItem = 195;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Mora Meat", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem7ActionPerformed

    private void jButtonDrinkItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinkItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDrinkItem7ActionPerformed

    private void jButtonFoodItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem2ActionPerformed
        double PriceOfItem = 150;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Black Back Perch Stew", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem2ActionPerformed

    private void jButtonFoodItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem3ActionPerformed
        double PriceOfItem = 120;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Crab Roe Tofu", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem3ActionPerformed

    private void jButtonFoodItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem4ActionPerformed
        double PriceOfItem = 80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Jade Parcels", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem4ActionPerformed

    private void jButtonFoodItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem5ActionPerformed
        double PriceOfItem = 240;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Jewelry Soup", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem5ActionPerformed

    private void jButtonFoodItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem6ActionPerformed
        double PriceOfItem = 95;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Jueyun", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem6ActionPerformed

    private void jButtonFoodItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem1ActionPerformed
        double PriceOfItem = 200;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Almond Tofu", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem1ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButtonFoodItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem8ActionPerformed
        double PriceOfItem = 333;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Noodle Delicacy", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem8ActionPerformed

    private void jButtonFoodItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoodItem9ActionPerformed
        double PriceOfItem = 450;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Squirrel Fish", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonFoodItem9ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButtonDrinkItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinkItem1ActionPerformed
        double PriceOfItem = 55;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Wolf Hook Juice", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDrinkItem1ActionPerformed

    private void jButtonDrinkItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinkItem2ActionPerformed
        double PriceOfItem = 45;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rainbow Aster", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDrinkItem2ActionPerformed

    private void jButtonDrinkItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinkItem3ActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"House Blend Iced Tea", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDrinkItem3ActionPerformed

    private void jButtonDrinkItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinkItem4ActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Dango Milk", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDrinkItem4ActionPerformed

    private void jButtonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignOutActionPerformed
        JFrame exit = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(exit, "Do you want to exit out?", "Point of Sale",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        	LoginForm lgf=new LoginForm();
			lgf.setVisible(true);
			lgf.setLocationRelativeTo(null);
			lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			this.dispose();
        }
        
    }//GEN-LAST:event_jButtonSignOutActionPerformed

    private void jButtonDrinkItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinkItem6ActionPerformed
        double PriceOfItem = 85;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Apple Cider", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDrinkItem6ActionPerformed

    private void jButtonDrinkItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrinkItem5ActionPerformed
        double PriceOfItem = 70;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Berry Mint Burst", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jButtonDrinkItem5ActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        FoodMenu3 fm = new FoodMenu3();
        fm.setLocationRelativeTo(null);
        fm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        DrinkMenu dm = new DrinkMenu();
        dm.setLocationRelativeTo(null);
        dm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoryActionPerformed
    	order.setVisible(true);
    	order.setLocationRelativeTo(null);
    	order.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.dispose();
    	

        
        
    }//GEN-LAST:event_jButtonHistoryActionPerformed

    private void jTextFieldSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubTotalActionPerformed

    private void jTextFieldDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiscountActionPerformed

    private void jTextFieldChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChangeActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
        Change();
    }//GEN-LAST:event_jButtonPayActionPerformed

    private void jButtonCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcActionPerformed
        calcu.setVisible(true);
        calcu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonCalcActionPerformed

    private void jButtonDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscountActionPerformed
        
        if(jButtonDiscount.isSelected()){
            Discount();
        } else {
            Change();
            jTextFieldDiscount.setText("0");
        }
        
    }//GEN-LAST:event_jButtonDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeScreen().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButtonAddOrder;
    private javax.swing.JButton jButtonCalc;
    private javax.swing.JButton jButtonDeleteOrder;
    private javax.swing.JToggleButton jButtonDiscount;
    private javax.swing.JButton jButtonDrinkItem1;
    private javax.swing.JButton jButtonDrinkItem2;
    private javax.swing.JButton jButtonDrinkItem3;
    private javax.swing.JButton jButtonDrinkItem4;
    private javax.swing.JButton jButtonDrinkItem5;
    private javax.swing.JButton jButtonDrinkItem6;
    private javax.swing.JButton jButtonDrinkItem7;
    private javax.swing.JButton jButtonFoodItem1;
    private javax.swing.JButton jButtonFoodItem2;
    private javax.swing.JButton jButtonFoodItem3;
    private javax.swing.JButton jButtonFoodItem4;
    private javax.swing.JButton jButtonFoodItem5;
    private javax.swing.JButton jButtonFoodItem6;
    private javax.swing.JButton jButtonFoodItem7;
    private javax.swing.JButton jButtonFoodItem8;
    private javax.swing.JButton jButtonFoodItem9;
    private javax.swing.JButton jButtonHistory;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JButton jButtonVoidItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCash;
    private javax.swing.JTextField jTextFieldChange;
    private javax.swing.JTextField jTextFieldDiscount;
    private javax.swing.JTextField jTextFieldSubTotal;
    // End of variables declaration//GEN-END:variables
}
